### ISSUE TITLE
[Bug]: CDC create curl: (52) Empty reply from server

### ISSUE THREAD

**Issue by 670248996** [zilliztech/milvus-cdc#141]
### Current Behavior

standalone部署主从环境milvus，使用cdc同步数据，curl发送create请求等待一段时间后报错 Current Behavior
A concise description of what you're experiencing.
cdc请求
```
wangqiang@ubuntu:/milvus-cdc$ curl -X POST http://localhost:8444/cdc \
> -H "Content-Type: application/json" \
> -d '{
>   "request_type": "create",
>   "request_data": {
>     "milvus_connect_param": {
>       "host": "192.168.5.113",
>       "port": 19530,
>       "token":"root:Milvus",
>       "connect_timeout": 10
>     },
>     "collection_infos": [
>       {
>         "name": "*"
>       }
>     ],
>     "rpc_channel_info": {
>       "name": "test113"
>     }
>   }
> }'
curl: (52) Empty reply from server
wangqiang@ubuntu:/milvus-cdc$ curl -X POST -H "Content-Type: application/json" -d '{ocker-compose/milvus-cdc$ curl -X POST -H "Conten
>   "request_type": "list"
> }' http://localhost:8444/cdc
{"code":200,"data":{"tasks":[{"task_id":"a982c979e94c4ce0b7b8206c89660e9c","milvus_connect_param":{"host":"192.168.5.113","port":19530,"enable_tls":false,"dial_config":{"server_name":"","server_pem_path":"","ca_pem_path":"","client_pem_path":"","client_key_path":""},"ignore_partition":false,"connect_timeout":10},"collection_infos":[{"name":"*","positions":null}],"state":"Initial"}]}}

```
cdc日志
```

milvus-cdc  | address: 0.0.0.0:8444
milvus-cdc  | maxTaskNum: 100
milvus-cdc  | metaStoreConfig:
milvus-cdc  |   storeType: etcd
milvus-cdc  |   etcd:
milvus-cdc  |     address:
milvus-cdc  |       - http://192.168.5.114:2379
milvus-cdc  |     enableAuth: false
milvus-cdc  |     username: root
milvus-cdc  |     password: root123456
milvus-cdc  |     enableTLS: false
milvus-cdc  |     tlsCertPath: deployment/cert/client.pem # path to your cert file
milvus-cdc  |     tlsKeyPath: deployment/cert/client.key # path to your key file
milvus-cdc  |     tlsCACertPath: deployment/cert/ca.pem # path to your CACert file
milvus-cdc  |     tlsMinVersion: 1.3
milvus-cdc  |   rootPath: cdc-dev1
milvus-cdc  | sourceConfig:
milvus-cdc  |   etcd:
milvus-cdc  |     address:
milvus-cdc  |       - http://192.168.5.114:2379
milvus-cdc  |     rootPath: by-dev
milvus-cdc  |     metaSubPath: meta
milvus-cdc  |     enableAuth: false
milvus-cdc  |     username: root
milvus-cdc  |     password: root123456
milvus-cdc  |     enableTLS: false
milvus-cdc  |     tlsCertPath: deployment/cert/client.pem # path to your cert file
milvus-cdc  |     tlsKeyPath: deployment/cert/client.key # path to your key file
milvus-cdc  |     tlsCACertPath: deployment/cert/ca.pem # path to your CACert file
milvus-cdc  |     tlsMinVersion: 1.3
milvus-cdc  |   readChanLen: 4
milvus-cdc  |   defaultPartitionName: _default
milvus-cdc  |   replicateChan: by-dev-replicate-msg
milvus-cdc  |   pulsar:
milvus-cdc  |     address: pulsar://192.168.5.114:6650
milvus-cdc  |     webAddress: localhost:80
milvus-cdc  |     maxMessageSize: 5242880
milvus-cdc  |     tenant: public
milvus-cdc  |     namespace: default
milvus-cdc  | #    authPlugin: org.apache.pulsar.client.impl.auth.AuthenticationToken
milvus-cdc  | #    authParams: token:xxx
milvus-cdc  | #  kafka:
milvus-cdc  | #    address: 127.0.0.1:9092
milvus-cdc  | maxNameLength: 256
milvus-cdc  | logLevel: info
milvus-cdc  | [2024/10/12 09:49:08.597 +00:00] [INFO] [paramtable/component_param.go:3874] ["DeployModeEnv is not set, use default"] [default=0.5]
milvus-cdc  | [2024/10/12 09:49:08.598 +00:00] [INFO] [paramtable/hook_config.go:21] ["hook config"] [hook={}]
milvus-cdc  | [2024/10/12 09:49:08.599 +00:00] [INFO] [tag/tag.go:34] ["base info"] [BuildTime="Mon Aug 12 11:52:16 UTC 2024"] [GitCommit=] [GoVersion="go version go1.21.13 linux/amd64"]
milvus-cdc  | [2024/10/12 09:49:08.611 +00:00] [INFO] [server/server.go:56] ["start server..."]
milvus-cdc  | [2024/10/12 09:49:28.510 +00:00] [INFO] [reader/etcd_op.go:772] ["current time"] [ts=2024/10/12 09:49:29.325 +00:00]
milvus-cdc  | [2024/10/12 09:49:28.512 +00:00] [INFO] [reader/etcd_op.go:566] ["get all collection data"] [count=13]
milvus-cdc  | [2024/10/12 09:49:28.515 +00:00] [INFO] [reader/etcd_op.go:707] ["get all partition data"] [partition_num=137]
milvus-cdc  | [2024/10/12 09:49:28.516 +00:00] [INFO] [writer/channel_writer.go:73] ["new channel writer"] [droppedObjs="{\"collection\":{\"openSet_OpenSetGuardianshipLeaving_1843851601308028929_d\":453175297789132799,\"openSet_OpenSetGuardianshipLeaving_1844650019043414018_d\":453175297789132799},\"database\":{},\"partition\":{}}"]
milvus-cdc  | [2024/10/12 09:49:28.517 +00:00] [INFO] [msgdispatcher/manager.go:66] ["create new dispatcherManager"] [role=cdc] [nodeID=8444] [pchannel=test113]
milvus-cdc  | [2024/10/12 09:49:28.517 +00:00] [INFO] [msgdispatcher/dispatcher.go:93] ["creating dispatcher..."] [pchannel=test113] [subName=cdc-8444-test113_a982c979e94c4ce0b7b8206c89660e9cv0-true] [isMain=true]
milvus-cdc  | [2024/10/12 09:49:28.517 +00:00] [INFO] [msgdispatcher/manager.go:153] ["dispatcherManager is running..."] [role=cdc] [nodeID=8444] [pchannel=test113]
milvus-cdc  | [2024/10/12 09:49:28.517 +00:00] [INFO] [msgstream/mq_msgstream.go:117] ["Msg Stream state"] [can_produce=true]
milvus-cdc  | [2024/10/12 09:49:30.222 +00:00] [WARN] [retry/retry.go:46] ["retry func failed"] [retried=0] [error="server error: PersistenceError: org.apache.bookkeeper.mledger.ManagedLedgerException: Not enough non-faulty bookies available"]
milvus-cdc  | [2024/10/12 09:49:33.288 +00:00] [WARN] [retry/retry.go:46] ["retry func failed"] [retried=4] [error="server error: PersistenceError: org.apache.bookkeeper.mledger.ManagedLedgerException: Not enough non-faulty bookies available"]
milvus-cdc  | [2024/10/12 09:49:51.555 +00:00] [WARN] [retry/retry.go:46] ["retry func failed"] [retried=8] [error="server error: PersistenceError: org.apache.bookkeeper.mledger.ManagedLedgerException: Not enough non-faulty bookies available"]
milvus-cdc  | [2024/10/12 09:50:11.623 +00:00] [WARN] [retry/retry.go:46] ["retry func failed"] [retried=12] [error="server error: PersistenceError: org.apache.bookkeeper.mledger.ManagedLedgerException: Not enough non-faulty bookies available"]
milvus-cdc  | [2024/10/12 09:50:31.683 +00:00] [WARN] [retry/retry.go:46] ["retry func failed"] [retried=16] [error="server error: PersistenceError: org.apache.bookkeeper.mledger.ManagedLedgerException: Not enough non-faulty bookies available"]
milvus-cdc  | [2024/10/12 09:50:51.748 +00:00] [INFO] [server/cdc_impl.go:179] ["create request done"]
milvus-cdc  | 2024/10/12 09:50:51 http: panic serving 192.168.128.1:19380: Failed to create consumer test113, errors = server error: PersistenceError: org.apache.bookkeeper.mledger.ManagedLedgerException: Not enough non-faulty bookies available
milvus-cdc  | goroutine 344 [running]:
milvus-cdc  | net/http.(*conn).serve.func1()
milvus-cdc  | 	/usr/local/go/src/net/http/server.go:1873 +0xb9
milvus-cdc  | panic({0x1776e60?, 0xc000a52e70?})
milvus-cdc  | 	/usr/local/go/src/runtime/panic.go:920 +0x270
milvus-cdc  | github.com/milvus-io/milvus/pkg/mq/msgstream.(*mqMsgStream).AsConsumer(0xc00062ed20, {0x1c77bb0, 0x296a6c0}, {0xc000cc44d0?, 0x1, 0x0?}, {0xc000791740, 0x38}, 0x0)
milvus-cdc  | 	/go/pkg/mod/github.com/!sim!f!g/milvus/pkg@v0.0.0-20240727040408-64020f3da23b/mq/msgstream/mq_msgstream.go:205 +0x5d4
milvus-cdc  | github.com/milvus-io/milvus/pkg/mq/msgdispatcher.NewDispatcher({0x1c77bb0, 0x296a6c0}, {0x1c6df90, 0xc000d32300}, 0x1, {0xc000ca4a20, 0x7}, 0x0, {0xc000791740, 0x38}, ...)
milvus-cdc  | 	/go/pkg/mod/github.com/!sim!f!g/milvus/pkg@v0.0.0-20240727040408-64020f3da23b/mq/msgdispatcher/dispatcher.go:116 +0xa32
milvus-cdc  | github.com/milvus-io/milvus/pkg/mq/msgdispatcher.(*dispatcherManager).Add(0xc000c7e750, {0x1c77bb0, 0x296a6c0}, {0xc000ca4a20, 0x2a}, 0xc000c7e750?, 0xc000d32300?)
milvus-cdc  | 	/go/pkg/mod/github.com/!sim!f!g/milvus/pkg@v0.0.0-20240727040408-64020f3da23b/mq/msgdispatcher/manager.go:92 +0x485
milvus-cdc  | github.com/milvus-io/milvus/pkg/mq/msgdispatcher.(*client).Register(0xc0009a8380, {0x1c77bb0, 0x296a6c0}, {0xc000ca4a20, 0x2a}, 0x7f6485b70a68?, 0xc000cb2580?)
milvus-cdc  | 	/go/pkg/mod/github.com/!sim!f!g/milvus/pkg@v0.0.0-20240727040408-64020f3da23b/mq/msgdispatcher/client.go:78 +0x4d4
milvus-cdc  | github.com/zilliztech/milvus-cdc/core/reader.NewChannelReader({0xc0008b4378, 0x7}, {0x0, 0x0}, {0x1c6f010?, 0xc0009a8380}, {0xc000ab4780, 0x20}, 0xc000ac5c70)
milvus-cdc  | 	/app/core/reader/channel_reader.go:82 +0x3b7
milvus-cdc  | github.com/zilliztech/milvus-cdc/server.(*MetaCDC).getChannelReader(0xc0009960a0, 0xc000250dc0, 0xc000c6ad00, {0xc0008b4378, 0x7}, {0x0, 0x0})
milvus-cdc  | 	/app/server/cdc_impl.go:864 +0x312
milvus-cdc  | github.com/zilliztech/milvus-cdc/server.(*MetaCDC).startInternal(0xc0009960a0, 0xc000250dc0, 0x0)
milvus-cdc  | 	/app/server/cdc_impl.go:519 +0xad6
milvus-cdc  | github.com/zilliztech/milvus-cdc/server.(*MetaCDC).Create(0xc0009960a0, 0xc0002ec690)
milvus-cdc  | 	/app/server/cdc_impl.go:335 +0x1087
milvus-cdc  | github.com/zilliztech/milvus-cdc/server.init.0.func2({0x1c835b8?, 0xc0009960a0?}, {0x1740b80?, 0xc0002ec690?})
milvus-cdc  | 	/app/server/handle_map.go:45 +0x3a
milvus-cdc  | github.com/zilliztech/milvus-cdc/server.(*CDCServer).handleRequest(0xc00096dd70, 0xc00096c5e8, {0x1c6e280, 0xc0007761c0})
milvus-cdc  | 	/app/server/server.go:129 +0x183
milvus-cdc  | github.com/zilliztech/milvus-cdc/server.(*CDCServer).Run.(*CDCServer).getCDCHandler.func2({0x1c6e280, 0xc0007761c0}, 0xc000b94300)
milvus-cdc  | 	/app/server/server.go:86 +0x368
milvus-cdc  | net/http.HandlerFunc.ServeHTTP(0x10?, {0x1c6e280?, 0xc0007761c0?}, 0xc00058812c?)
milvus-cdc  | 	/usr/local/go/src/net/http/server.go:2141 +0x29
milvus-cdc  | net/http.(*ServeMux).ServeHTTP(0x416d05?, {0x1c6e280, 0xc0007761c0}, 0xc000b94300)
milvus-cdc  | 	/usr/local/go/src/net/http/server.go:2519 +0x142
milvus-cdc  | net/http.serverHandler.ServeHTTP({0x1c6a718?}, {0x1c6e280?, 0xc0007761c0?}, 0x6?)
milvus-cdc  | 	/usr/local/go/src/net/http/server.go:2943 +0x8e
milvus-cdc  | net/http.(*conn).serve(0xc000708630, {0x1c77d08, 0xc000d0d290})
milvus-cdc  | 	/usr/local/go/src/net/http/server.go:2014 +0x5f4
milvus-cdc  | created by net/http.(*Server).Serve in goroutine 1
milvus-cdc  | 	/usr/local/go/src/net/http/server.go:3091 +0x5cb

```

### Steps To Reproduce

```
curl -X POST http://localhost:8444/cdc \
-H "Content-Type: application/json" \
-d '{
  "request_type": "create",
  "request_data": {
    "milvus_connect_param": {
      "host": "192.168.5.113",
      "port": 19530,
      "token":"root:Milvus",
      "connect_timeout": 10
    },
    "collection_infos": [
      {
        "name": "*"
      }
    ],
    "rpc_channel_info": {
      "name": "test113"
    }
  }
}'

报错curl: (52) Empty reply from server
```

### Environment

1. milvus主节点docker-compose.yml（114机器）
```
version: '3.5'
services:
  etcd:
    container_name: milvus-etcd-2.4.12
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    container_name: milvus-minio-2.4.12
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9101:9001"
      - "9110:9000"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone-2.4.12
    image: milvusdb/milvus:v2.4.12
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      PULSAR_ADDRESS: pulsar://pulsar:6650
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9891:9091"
    depends_on:
      - "etcd"
      - "minio"
      - "pulsar"

  pulsar:
    container_name: milvus-pulsar-2.4.12
    image: apachepulsar/pulsar:2.10.2
    environment:
      - nettyMaxFrameSizeBytes=104867840 # this is 104857600 + 10240 (padding)
      - defaultRetentionTimeInMinutes=10080
      - defaultRetentionSizeInMB=8192
      - PULSAR_PREFIX_maxMessageSize=104857600
      - PULSAR_GC=-XX:+UseG1GC
    command: |
      /bin/bash -c \
      "bin/apply-config-from-env.py conf/standalone.conf && \
      exec bin/pulsar standalone --no-functions-worker --no-stream-storage"
    ports:
      - "6650:6650"
      - "8088:8080"
networks:
  default:
    name: milvus-2.4.12
```

2. milvus从节点docker-compose.yml（113机器）
```
version: '3.5'
services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    ports:
      - "23790:2379"
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9009:9000"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.4.12
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      PULSAR_ADDRESS: pulsar://pulsar:6650
      common.ttMsgEnabled: false
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"

  pulsar:
    container_name: milvus-pulsar
    image: apachepulsar/pulsar:2.10.2
    environment:
      - nettyMaxFrameSizeBytes=104867840 # this is 104857600 + 10240 (padding)
      - defaultRetentionTimeInMinutes=10080
      - defaultRetentionSizeInMB=8192
      - PULSAR_PREFIX_maxMessageSize=104857600
      - PULSAR_GC=-XX:+UseG1GC
    command: |
      /bin/bash -c \
      "bin/apply-config-from-env.py conf/standalone.conf && \
      exec bin/pulsar standalone --no-functions-worker --no-stream-storage"
    ports:
      - "6650:6650"
      - "8080:8080"

networks:
  default:
    name: milvus
```

3. milvus-cdc节点docker-compose.yml（114机器）
```
services:
  milvus-cdc:
    container_name: milvus-cdc
    image: milvusdb/milvus-cdc:latest
    tty: true
    ports:
      - "8444:8444"
    volumes:
      - type: bind
        source: ./cdc.yaml
        target: /app/configs/cdc.yaml
        read_only: true
```

4. milvus-cdc配置文件cdc.yaml（114机器）
```
address: 0.0.0.0:8444
maxTaskNum: 100
metaStoreConfig:
  storeType: etcd
  etcd:
    address:
      - http://192.168.5.114:2379
    enableAuth: false
    username: root
    password: root123456
    enableTLS: false
    tlsCertPath: deployment/cert/client.pem # path to your cert file
    tlsKeyPath: deployment/cert/client.key # path to your key file
    tlsCACertPath: deployment/cert/ca.pem # path to your CACert file
    tlsMinVersion: 1.3
  rootPath: cdc-dev1
sourceConfig:
  etcd:
    address:
      - http://192.168.5.114:2379
    rootPath: by-dev
    metaSubPath: meta
    enableAuth: false
    username: root
    password: root123456
    enableTLS: false
    tlsCertPath: deployment/cert/client.pem # path to your cert file
    tlsKeyPath: deployment/cert/client.key # path to your key file
    tlsCACertPath: deployment/cert/ca.pem # path to your CACert file
    tlsMinVersion: 1.3
  readChanLen: 4
  defaultPartitionName: _default
  replicateChan: by-dev-replicate-msg
  pulsar:
    address: pulsar://192.168.5.114:6650
    webAddress: localhost:80
    maxMessageSize: 5242880
    tenant: public
    namespace: default
#    authPlugin: org.apache.pulsar.client.impl.auth.AuthenticationToken
#    authParams: token:xxx
#  kafka:
#    address: 127.0.0.1:9092
maxNameLength: 256
logLevel: info
```
